name: Build and Publish Docker Image

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'x86_64', dockerPlatform: 'linux/amd64' }
          - { name: 'aarch64', dockerPlatform: 'linux/arm64' }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set env
        run: |
          (echo "${GITHUB_REF}" | grep "refs/tags" >/dev/null && echo "IMAGE_VERSION=tag-${GITHUB_REF#refs/*/v}" || echo "IMAGE_VERSION=commit-${GITHUB_SHA::8}") >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-${{ matrix.platform.name }}-buildx01-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ matrix.platform.name }}-buildx01-"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform.dockerPlatform }}
          context: .
          file: linux.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          target: assets
          outputs: type=local,dest=out
          build-args: |
            ARCH=${{ matrix.platform.name }}

      - name: Push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform.dockerPlatform }}
          context: .
          file: linux.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache-new
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            ARCH=${{ matrix.platform.name }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/appimagekit:latest-${{ matrix.platform.name }}
            ghcr.io/${{ github.repository_owner }}/appimagekit:${{ env.IMAGE_VERSION }}-${{ matrix.platform.name }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: appimagetool-${{ matrix.platform.name }}.build
          path: out/

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ls -al
          ./pyuploadtool-x86_64.AppImage appimagetool-*.build/*
